# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', jsonfield.fields.JSONField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
                'ordering': ['-created'],
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
    ]
