# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0005_auto_20180202_1318'),
        ('assignments', '0003_candidate_weight'),
        ('openslides_voting', '0003_auto_20180327_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingToken',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
            ],
            options={
                'default_permissions': (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MotionPollType',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    default='analog', max_length=128)),
                ('poll', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='motions.MotionPoll')),
            ],
            options={
                'default_permissions': (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssignmentPollBallot',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(
                    blank=True, max_length=1)),
                ('delegate', models.ForeignKey(
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='assignments.AssignmentPoll')),
                ('resultToken', models.PositiveIntegerField(
                    default=0)),
            ],
            options={
                'default_permissions': (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssignmentPollType',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    default='analog', max_length=128)),
                ('poll', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='assignments.AssignmentPoll')),
            ],
            options={
                'default_permissions': (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='motionpollballot',
            name='resultToken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motionpollballot',
            name='delegate',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentpollballot',
            unique_together=set([('poll', 'delegate')]),
        ),
    ]
