# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_voting', '0004_motionpolltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpollballot',
            name='device',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='motionpollballot',
            name='device',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
