# Generated by Django 2.1 on 2018-08-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_voting', '0005_auto_20180730_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentpolltype',
            name='type',
            field=models.CharField(
                choices=[
                    ('analog', 'Analog voting'),
                    ('named_electronic', 'Named electronic voting'),
                    ('token_based_electronic', 'Token-based electronic voting'),
                    ('votecollector', 'VoteCollector'),
                    ('votecollector_anonymous', 'VoteCollector anonymous')
                ],
                default='analog',
                max_length=32
            ),
        ),
        migrations.AlterField(
            model_name='motionpolltype',
            name='type',
            field=models.CharField(
                choices=[
                    ('analog', 'Analog voting'),
                    ('named_electronic', 'Named electronic voting'),
                    ('token_based_electronic', 'Token-based electronic voting'),
                    ('votecollector', 'VoteCollector'),
                    ('votecollector_anonymous', 'VoteCollector anonymous')
                ],
                default='analog',
                max_length=32
            ),
        ),
    ]
