# Generated by Django 2.1 on 2018-09-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_voting', '0006_auto_20180816_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentpolltype',
            name='type',
            field=models.CharField(
                choices=[
                    ('analog', 'Analog voting'),
                    ('named_electronic', 'Named electronic voting'),
                    ('token_based_electronic', 'Token-based electronic voting'),
                    ('votecollector', 'VoteCollector'),
                    ('votecollector_anonymous', 'VoteCollector anonymous'),
                    ('votecollector_secret', 'VoteCollector secret voting'),
                    ('votecollector_pseudo_secret', 'VoteCollector pseudo-secret voting')
                ],
                default='analog',
                max_length=32),
        ),
        migrations.AlterField(
            model_name='motionpolltype',
            name='type',
            field=models.CharField(
                choices=[
                    ('analog', 'Analog voting'),
                    ('named_electronic', 'Named electronic voting'),
                    ('token_based_electronic', 'Token-based electronic voting'),
                    ('votecollector', 'VoteCollector'),
                    ('votecollector_anonymous', 'VoteCollector anonymous'),
                    ('votecollector_secret', 'VoteCollector secret voting'),
                    ('votecollector_pseudo_secret', 'VoteCollector pseudo-secret voting')],
                default='analog',
                max_length=32),
        ),
    ]
