# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_voting', '0007_auto_20180904_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentpolltype',
            name='type',
            field=models.CharField(choices=[('analog', 'Analog voting'), ('named_electronic', 'Named electronic voting'), ('token_based_electronic', 'Token-based electronic voting'), ('votecollector', 'VoteCollector default (personalized and active keypads only, with single votes)'), ('votecollector_secret', 'VoteCollector secret (no single votes and delegate board)'), ('votecollector_pseudo_secret', 'VoteCollector grey (no single votes, only grey seats on delegate board)'), ('votecollector_anonymous', 'VoteCollector anonymous (anonymous and personalized keypads, with single votes, no delegate board)')], default='analog', max_length=32),
        ),
        migrations.AlterField(
            model_name='motionpolltype',
            name='type',
            field=models.CharField(choices=[('analog', 'Analog voting'), ('named_electronic', 'Named electronic voting'), ('token_based_electronic', 'Token-based electronic voting'), ('votecollector', 'VoteCollector default (personalized and active keypads only, with single votes)'), ('votecollector_secret', 'VoteCollector secret (no single votes and delegate board)'), ('votecollector_pseudo_secret', 'VoteCollector grey (no single votes, only grey seats on delegate board)'), ('votecollector_anonymous', 'VoteCollector anonymous (anonymous and personalized keypads, with single votes, no delegate board)')], default='analog', max_length=32),
        ),
    ]
